---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
data:
  sausage-store.yaml: |
    ---
    groups:
      - name: Sausage store rules
        rules:
          - alert: InstanceDown
            expr: up{app="backend"} == 0
            for: 1m
            labels:
              severity: critical
              project: "sausage_store"
              component: "Backend"
            annotations:
              summary: "Backend instance is down"
              description: "Backend of namespace std-026-35 is unanavailable more than 1 min"

          - alert: 5xxErrors
            expr: sum(http_server_requests_seconds_count{status="500"})
            for: 1m
            labels:
              severity: critical
              project: "sausage_store"
              component: "Backend"
            annotations:
              summary: "5xx error codes"
              description: "5xx error have been found in the last minute"

          - alert: HighLatency
            expr: quantile(0.95,http_server_requests_seconds_max{uri="/api/orders", method="POST"}) >=0.1
            for: 1m
            labels:
              severity: warning
              project: "sausage_store"
              component: "Backend"
            annotations:
              summary: "Latency is rising"
              description: "Latency issues. More than 100 in the last minute"

          - alert: ActuatorError
            expr: http_server_requests_seconds_count{uri="/actuator/prometheus", status=~"4..|5.."}
            for: 1m
            labels:
              severity: warning
              project: "sausage_store"
              component: "Backend"
            annotations:
              summary: "Errors from actuator"
              description: "4xx|5xx response codes from actuator"
