# Обновление пакетов системы
- name: updating packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
  become: true

# Установка nginx
- name: install nginx
  apt:
    pkg:
    - nginx
  become: true

# Добавление сервисного пользователя для фронтенда
- name: frontend service account setup
  user:
    name: "{{ frontend_service_user }}"
    create_home: no
    shell: /sbin/nologin
  become: true

# Скачивание исполняемого файла бэкенда из хранилища nexus
- name: download frontend archive file from nexus
  get_url:
    username: "{{ nexus_username }}"
    password:  "{{ nexus_password }}"
    dest: "{{ frontend_working_directory }}sausage-store.jar"
    repository_url: 
      - >
        "http://nexus.praktikum-services.tech/repository/std-026-35-frontend2/
        {{ nexus_archive_version }}/sausage-store-{{ nexus_archive_version }}.tar.gz"
  become: true