---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLmRwYjZjNFBHUmtOajRLRWJtY3hmamxEaQ==
type: Opaque


---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsKICAgICAgICAgICAgImF1dGgiOiJjM1JrTFRBeU5pMHpOVHB3TTNwUWFtRnBiMUZWVFdNNU5XTklWRVJvWVE9PSIKICAgICAgICB9CiAgICB9Cn0=
type: kubernetes.io/dockerconfigjson
