stages:
  - build
  - deploy

build-and-push-helm-package:
  stage: build
  image: dtzar/helm-kubectl
  script:
    - helm package sausage-store-chart/
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} -o sausage-store-0.1.0.tgz http://nexus.praktikum-services.tech/repository/std-026-35-helm/

deploy:
  stage: deploy
  image: argoproj/argocd:v2.12.0
  script:
    - argocd --grpc-web --auth-token $ARGO_TOKEN --server $ARGO_SERVER app sync sausage-store-std-026-35
