# Добавление сервисного пользователя для бэкенда
- name: backend service account setup
  user:
    name: "{{ backend_service_user }}"
    create_home: no
    shell: /sbin/nologin
  become: true

# Создание юнит файла бэкенда
- name: create sausage-store-backend.service
  template:
    src: sausage-store-backend.service.j2
    dest: /etc/systemd/system/sausage-store-backend.service
  become: true

# Обновляем конфигурацию systemd для запуска бэкенд юнита
- name: reloading systemd daemons
  systemd:
    daemon_reload: yes
  become: true

# Запуск бэкенд юнита
- name: start of sausage-store-backend.service
service:
  name: sausage-store-backend
  state: started
become: true