---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.vault_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: sausage-store
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    meta.helm.sh/release-name: "sausage-store"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
data:
  vault_token: {{ .Values.secrets.vault_token }}
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: {{ .Values.secrets.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson

