---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.vpa.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: sausage-store
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    meta.helm.sh/release-name: "sausage-store"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Values.vpa.name }}
  updatePolicy:
    updateMode: "{{ .Values.vpa.updateMode }}"
  resourcePolicy:
    containerPolicies:
      - containerName: "{{ .Values.vpa.containerName }}"
        minAllowed:
          cpu: {{ .Values.vpa.minAllowed.cpu }}
          memory: {{ .Values.vpa.minAllowed.memory }}
        maxAllowed:
          cpu: {{ .Values.vpa.maxAllowed.cpu }}
          memory: {{ .Values.vpa.maxAllowed.memory }}
        controlledResources: {{ .Values.vpa.controlledResources }}
        controlledValues: {{ .Values.vpa.controlledValues }}
