stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.30.3
  environment:
    name: kubernetes
    url: https://std-026-35.praktikum-services.tech
  before_script:
    - mkdir -p ~/.kube
    - echo ${KUBECONFIG} | base64 -d > ~/.kube/config
    - cat ~/.kube/config
    - KUBECONFIG=~/.kube/config
    - export KUBECONFIG
  script:
    - kubectl apply -f kubernetes/backend/
    - kubectl apply -f kubernetes/backend-report/
    - kubectl apply -f kubernetes/frontend/
    - rm -f ~/.kube/config