---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: gitlab.praktikum-services.ru:5050/std-026-35/sausage-store/sausage-backend-report:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_HOST
              value: "http://std-026-35.praktikum-services.tech:8200/"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
          ports:
            - name: backend-report
              containerPort: 8080
      imagePullSecrets:
        - name: docker-config-secret