---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 1
  revisionHistoryLimit: 12
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: gitlab.praktikum-services.ru:5050/std-026-35/sausage-store/backend-report_kubernetes:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: spring_data_mongodb_uri
          ports:
            - name: backend-report
              containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: 0.1
            limits:
              memory: "256Mi"
              cpu: 0.2
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                  - key: availability-zone
                    operator: In
                    values:
                      - zone1
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - backend-report
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker-config-secret